name: ritaj_compound
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  animations: ^2.0.11
  awesome_dio_interceptor: ^1.3.0
  cached_network_image: ^3.4.1
  dio: ^5.7.0
  flutter_bloc: ^9.0.0
  flutter_screenutil: ^5.9.3
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^8.0.3
  infinite_scroll_pagination: ^4.1.0
  intl: ^0.20.0
  logger: ^2.5.0
  pinput: ^5.0.1
  shimmer: ^3.0.0
  toastification: ^2.3.0
  flutter_gen: ^5.8.0
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.5
  flutter_dotenv: ^5.2.1
  fpdart: ^1.1.1
  go_router: ^14.6.3
  jwt_decoder: ^2.0.1
  upgrader: ^11.3.1
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  flutter_svg: ^2.0.17
  camera: ^0.11.0+2
  dropdown_button2: ^2.3.9
  file_picker: "^9.0.1"
  image_picker: ^1.0.7
  flutter_libphonenumber: ^2.7.0
  video_player: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.4
flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/gifs/
    - assets/videos/
    # - assets/lottie/

  fonts:
    - family: Alexandria
      fonts:
        - asset: assets/fonts/alex.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true
    lottie: true
